[package]
name = "day07"
version = "0.1.0"
authors = ["Martin Donlon <github-martin@donlons.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "0.1.6"
itertools = "0.8"
permutohedron = "0.2"